name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Install dependencies
      run: npm ci

    - name: Run Tests & Coverage
      run: npm run test

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unittests
        name: codecov-umbrella

    - name: Publish to NPM
      run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      continue-on-error: true # Continuer même si le package existe déjà (même version)

    - name: Run Cypress tests (Offline mode)
      uses: cypress-io/github-action@v7
      with:
        build: npm run build
        start: npm start
      env:
        CYPRESS_offline: true

    - name: Deploy to GitHub Pages
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git remote set-url origin https://x-access-token:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git
        npm run deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push frontend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend -f DockerfileReact .
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend

    - name: Build and push backend
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend -f server/Dockerfile ./server
        docker push ${{ secrets.DOCKER_USERNAME }}/backend

  test-docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create dummy env files
      run: |
        echo "MYSQL_ROOT_PASSWORD=root" > database/.env
        echo "MYSQL_HOST=db" > server/.env
        echo "MYSQL_PORT=3306" >> server/.env
        echo "MYSQL_DATABASE=ynov_ci" >> server/.env
        echo "MYSQL_USER=root" >> server/.env
        echo "MYSQL_PASSWORD=root" >> server/.env
        echo "JWT_SECRET=dummy" >> server/.env
        echo "ADMIN_EMAIL=admin@test.com" >> server/.env
        echo "ADMIN_PASSWORD=dummy" >> server/.env

    - name: Start Docker Compose
      working-directory: ./database
      run: docker compose up -d

    - name: Check Docker containers
      working-directory: ./database
      run: docker ps

    - name: Wait for services to start
      run: sleep 60

    - name: Run Infrastructure Tests - Check API
      run: docker inspect --format "{{json .State.Health.Status }}" database-api-1 | jq -e '. == "healthy"'

    - name: Run Infrastructure Tests - Check Database
      run: docker inspect --format "{{json .State.Health.Status }}" database-db-1 | jq -e '. == "healthy"'

    - name: Run Infrastructure Tests - Check React
      run: docker inspect --format "{{json .State.Health.Status }}" database-react-1 | jq -e '. == "healthy"'

    - name: Run Infrastructure Tests - Check Adminer
      run: docker inspect --format "{{json .State.Health.Status }}" database-adminer-1 | jq -e '. == "healthy"'

  deploy-vercel:
    runs-on: ubuntu-latest
    needs: [test-and-deploy, test-docker]
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Backend to Vercel
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
        run: |
          npm install -g vercel
          vercel deploy --prod --token $VERCEL_TOKEN --yes
